apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino-sample
spec:
  listener:
    tls:
      enabled: true
      certSecretRef:
        name: authorino-server-cert # kubernetes secret must contain 'tls.crt' and 'tls.key' entries
  oidcServer:
    tls:
      enabled: true
      certSecretRef:
        name: authorino-oidc-server-cert # kubernetes secret must contain 'tls.crt' and 'tls.key' entries
