name: Test

on:
  push:
    branches: [ 'main', 'master' ]

  pull_request:
    branches: [ 'main', 'master' ]

jobs:
  verify-manifests:
    name: Verify manifests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run make verify-manifests
        run: |
          make verify-manifests

  verify-fmt:
    name: Verify fmt
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run make verify-fmt
        run: |
          make verify-fmt

  test-scripts:
    name: Test Scripts
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        platform: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run make operator-sdk
        run: |
          make operator-sdk
